### ISSUE TITLE
Improve the ontology model

### ISSUE THREAD

**Issue by KMax** [ailabitmo/ceur-ws-lod#2]
Last year we did not have enough time to build a good ontology model to encode the crawled data, so this year we should improve it by reviewing works presented in the challenge. Ontology model from the last year is [here](https://github.com/ailabitmo/sempubchallenge2014-task1/wiki/Data-representation).

Works to look at:
- http://link.springer.com/chapter/10.1007/978-3-319-12024-9_10
- http://link.springer.com/chapter/10.1007/978-3-319-12024-9_15

**Comment by KMax** [comment]
E.g. we have a problem with representing a series of workshops. Now we use `rdfs:seeAlso` property to link workshop to the previous ones in the series. It's clear that `rdfs:seeAlso` is not very suitable for that, so maybe we could find a better property.

```
<http://ceur-ws.org/resource/workshop/1081> a bibo:Workshop ;
    rdfs:label "Workshop on Modular Ontologies 2013"^^xsd:string ;
    swc:isSubEventOf <http://ceur-ws.org/resource/conference/LPNMR-2013> ;
    timeline:atDate "2013-09-15"^^xsd:date ;
    bibo:shortTitle "WoMO"^^xsd:string ;
    swrc:edition 7 ;
    rdfs:seeAlso <http://ceur-ws.org/resource/workshop/232>,
        <http://ceur-ws.org/resource/workshop/315>,
        <http://ceur-ws.org/resource/workshop/875> .
```

**Comment by ghost** [comment]
Done. See files `ceur-ws-crawler/ontology_example.ttl` and `ceur-ws-crawler/alignments.ttl`.
